stages:
  - .pre
  - build
  - deploy

workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "master" && $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_TAG'
      when: never
    - if: $CI_COMMIT_BRANCH
      when: always
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always

before_script:
  - GRADLE_USER_HOME="$(pwd)/.gradle"
  - export GRADLE_USER_HOME

include:
  - project: 'org.salgar.fsm.akka/ci-cd-gitlab-pipelines'
    file: '/jobs/gitversion-ci-cd-plugin-extension.gitlab-ci.yml'
  - project: 'org.salgar.fsm.akka/ci-cd-gitlab-pipelines'
    file: '/jobs/gradle.yml'
  - project: 'org.salgar.fsm.akka/ci-cd-gitlab-pipelines'
    file: '/jobs/helm-push-service.yml'

variables:
  SERVICE_CHART_NAME: "credit-score-application"

determine-version:
  extends: .gitversion_function

continuous-deployment-development:
  stage: deploy
  needs:
    - job: determine-version
      artifacts: true
    - helm-push-service
  variables:
    BRANCH_NAME: $CI_COMMIT_BRANCH
    REPO_NAME: $CI_PROJECT_NAME
    VERSION: $GitVersion_SemVer
  trigger:
    project: 'org.salgar.fsm.akka/fsm-akka-helm-umbrella-chart-gitlab'
    strategy: depend
  rules:
    - if: '$CI_COMMIT_BRANCH == "development"'
      when: always
    - if: $CI_COMMIT_BRANCH
      when: never