stages:
  - .pre
  - build
  - deploy

services:
  - docker:dind

variables:
  DOCKER_HOST: DOCKER_HOST=tcp://docker:2375
  SOURCE_REPO: "credit-score"
  SERVICE_CHART_NAME: "credit-score-application"
  BUILD_VERSION: $GitVersion_SemVer
  GRADLE_COMMAND: "--build-cache --no-daemon build -Pversion="
  USE_CASE_1: "false"
  USE_CASE_2: "false"
  USE_CASE_3: "false"
  USE_CASE_4: "false"
  USE_CASE_5: "false"
  USE_CASE_6: "false"
  USE_CASE_7: "false"
  USE_CASE_8: "false"
  USE_CASE_9: "false"
  USE_CASE_10: "false"

workflow:
  rules:
    - if: $CI_COMMIT_REF_NAME == "development"
      when: always
      variables:
        USE_CASE_1: "true"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: always
      variables:
        USE_CASE_2: "true"
    - when: always

include:
  - project: 'org.salgar.fsm.akka/ci-cd-gitlab-pipelines'
    file: '/jobs/gitversion-ci-cd-plugin-extension.gitlab-ci.yml'
  - project: 'org.salgar.fsm.akka/ci-cd-gitlab-pipelines'
    file: '/jobs/gradle.yml'
  - project: 'org.salgar.fsm.akka/ci-cd-gitlab-pipelines'
    file: '/jobs/helm-push-service.yml'

determine-version:
  extends: .gitversion_function

continuous-deployment-development:
  stage: deploy
  needs:
    - job: determine-version
      artifacts: true
    - helm-push-service
  variables:
    BRANCH_NAME: $CI_COMMIT_BRANCH
    REPO_NAME: $CI_PROJECT_NAME
    SERVICE_CHART_VERSION: $GitVersion_SemVer
  trigger:
    project: 'org.salgar.fsm.akka/fsm-akka-helm-umbrella-chart-gitlab'
    branch: 'development'
    strategy: depend
  rules:
    - if: $USE_CASE_1 == "true"
      when: always
    - when: never

#continuous-deployment-pull-request-export:
#  stage: deploy
#  needs:
#    - job: determine-version
#      artifacts: true
#  variables:
#    BRANCH_NAME: $CI_COMMIT_REF_NAME
#    CREATE_BRANCH: "true"
#  script:
#    - |
#      export
#  rules:
#    - if: $USE_CASE_2 == "true"
#      when: always
#    - when: never
#  environment:
#    name: review/$CI_COMMIT_REF_SLUG
#    on_stop: cleanup-pull-request-environment

continuous-deployment-pull-request-create-branch:
  stage: deploy
  needs:
    - job: determine-version
      artifacts: true
  variables:
    BRANCH_NAME: $CI_COMMIT_REF_NAME
    CREATE_BRANCH: "true"
  trigger:
    project: 'org.salgar.fsm.akka/fsm-akka-helm-umbrella-chart-gitlab'
    branch: 'development'
    strategy: depend
  rules:
    - if: $USE_CASE_2 == "true"
      when: always
    - when: never

continuous-deployment-pull-request:
  stage: deploy
  needs:
    - job: determine-version
      artifacts: true
    - continuous-deployment-pull-request-create-branch
  variables:
    BRANCH_NAME: $CI_COMMIT_REF_NAME
    SERVICE_CHART_VERSION: $GitVersion_SemVer
  trigger:
    project: 'org.salgar.fsm.akka/fsm-akka-helm-umbrella-chart-gitlab'
    branch: 'feature/usecase2-credit-score'
    strategy: depend
  rules:
    - if: $USE_CASE_2 == "true"
      when: always
    - when: never

continuous-deployment-pull-request-prepare-environment:
  stage: deploy
  needs:
    - continuous-deployment-pull-request
  variables:
    BRANCH_NAME: $CI_COMMIT_REF_NAME-$SOURCE_REPO
  trigger:
    project: 'org.salgar.fsm.akka/fsm-akka-4eyes-argocd'
    branch: 'master'
    strategy: depend
  rules:
    - if: $USE_CASE_2 == "true"
      when: always
    - when: never

cleanup-pull-request-environment-argocd:
  stage: deploy
  needs:
    - continuous-deployment-pull-request-prepare-environment
  variables:
    TARGET_BRANCH_NAME: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
    BRANCH_NAME: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME-$SOURCE_REPO
    USE_CASE_3: "true"
  trigger:
    project: 'org.salgar.fsm.akka/fsm-akka-4eyes-argocd'
    branch: 'master'
    strategy: depend
#  environment:
#    name: review/$CI_COMMIT_REF_SLUG
#    action: stop
  rules:
    - if: $USE_CASE_2 == "true"
      when: manual
    - when: never

cleanup-pull-request-environment-environment-branch:
  stage: deploy
  needs:
    - continuous-deployment-pull-request-prepare-environment
  variables:
    USE_CASE_3: "true"
  trigger:
    project: 'org.salgar.fsm.akka/fsm-akka-dev-environment'
    branch: 'development'
    strategy: depend

cleanup-pull-request-environment-umbrella-chart-branch:
  stage: deploy
  needs:
    - continuous-deployment-pull-request-prepare-environment
  variables:
    USE_CASE_3: "true"
  trigger:
    project: 'org.salgar.fsm.akka/fsm-akka-helm-umbrella-chart-gitlab'
    branch: 'development'
    strategy: depend
