name: Cleanup Caller - Pull Request
run-name: Cleanup Environments after Pull Request for Branch ${{ github.event.pull_request.head.ref }} 
  triggered via ${{ github.event_name }} by ${{ github.actor }}
on:
  pull_request:
    types: [closed]
jobs:
  call-cleanup-workflow:
    uses: mehmetsalgar/fsm-akka-github-workflows/.github/workflows/cleanup-for-services.yaml@master
    with:
      repo-name: "credit-score"
      branch-name: "${{ github.event.pull_request.head.ref }}"
    secrets: inherit