name: Cleanup after Branch Delete
run-name: Cleanup after Branch Delete triggered via ${{ github.event_name }} by ${{ github.actor }}
on:
  delete:
jobs:
  print-start:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - run: |
          echo "start"
  call-cleanup-workflow:
    if: ${{ contains(github.ref, 'refs/heads/release/') }}
    uses: mehmetsalgar/fsm-akka-github-workflows/.github/workflows/cleanup-for-service.yaml@master
    needs: [print-start]
    with:
      repo-name: "credit-score"
      branch-name: "${{ github.event.ref }}"
    secrets: inherit
